version: '3.8'

networks:
  shared_net:

volumes:
  openldap_data:
  openldap_config:

services:
  consul:
    image: hashicorp/consul:1.18
    container_name: consul_gateway
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      - shared_net

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    container_name: keycloak
    command: ["start-dev", "--import-realm"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8090
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_BACKCHANNEL: "false"
    ports:
      - "8090:8080"
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import:ro
    networks:
      - shared_net
    depends_on:
      - openldap

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command: --copy-service
    environment:
      LDAP_ORGANISATION: Spring Framework
      LDAP_DOMAIN: springframework.org
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_BASE_DN: dc=springframework,dc=org
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
    networks:
      - shared_net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api_gateway
    ports:
      - "8000:8001"
    environment:
      SPRING_CLOUD_CONSUL_HOST: consul_gateway
      SPRING_CLOUD_CONSUL_PORT: "8500"
      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/finki-services/protocol/openid-connect/certs
      KEYCLOAK_ISSUER_URI: http://localhost:8090/realms/finki-services
    networks:
      - shared_net
    depends_on:
      - keycloak
      - consul
